export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

// login actiontypes 
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL= "LOGIN_FAIL";


export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL= "SIGNUP_FAIL";


export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT  = "LOG_OUT";

export const CLEAR_AUTH_STATE  = "CLEAR_AUTH_STATE";

export const EDITUSER_SUCCESS = "EDITUSER_SUCCESS";
export const EDITUSER_FAIL = "EDITUSER_FAIL";

export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_START = "USER_PROFILE_START";


export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const ADD_POST = "ADD_POST";